--By Mami
require("scripts.constants")
require("scripts.commands")
require("scripts.global")
require("scripts.lib")
require("scripts.factorio-api")
require("scripts.layout")
require("scripts.central-planning")
require("scripts.train-events")
require("scripts.gui")
require("scripts.migrations")
require("scripts.main")
require("scripts.remote-interface")
