--By Mami
data:extend({
	{
		type = "bool-setting",
		name = "cybersyn-enable-planner",
		order = "aa",
		setting_type = "runtime-global",
		default_value = true,
	},
	{
		type = "double-setting",
		name = "cybersyn-ticks-per-second",
		order = "ab",
		setting_type = "runtime-global",
		default_value = 30,
		minimum_value = 0,
		maximum_value = 60,
	},
	{
		type = "int-setting",
		name = "cybersyn-update-rate",
		order = "ac",
		setting_type = "runtime-global",
		default_value = 2,
		minimum_value = 1,
		maximum_value = 2147483647,
	},
	{
		type = "int-setting",
		name = "cybersyn-request-threshold",
		order = "ba",
		setting_type = "runtime-global",
		default_value = 2000,
		minimum_value = 1,
		maximum_value = 2147483647,
	},
	{
		type = "int-setting",
		name = "cybersyn-priority",
		order = "bb",
		setting_type = "runtime-global",
		default_value = 0,
		minimum_value = -2147483648,
		maximum_value = 2147483647,
	},
	{
		type = "int-setting",
		name = "cybersyn-locked-slots",
		order = "bc",
		setting_type = "runtime-global",
		default_value = 0,
		minimum_value = 0,
		maximum_value = 1000,
	},
	{
		type = "int-setting",
		name = "cybersyn-network-flag",
		order = "bd",
		setting_type = "runtime-global",
		default_value = -1,
		minimum_value = -2147483648,
		maximum_value = 2147483647,
	},
	{
		type = "double-setting",
		name = "cybersyn-fuel-threshold",
		order = "be",
		setting_type = "runtime-global",
		default_value = .5,
		minimum_value = -1,
		maximum_value = 1,
	},
	{
		type = "double-setting",
		name = "cybersyn-warmup-time",
		order = "ca",
		setting_type = "runtime-global",
		default_value = 20,
		minimum_value = 0,
		maximum_value = 2147483647,
	},
	{
		type = "double-setting",
		name = "cybersyn-stuck-train-time",
		order = "cb",
		setting_type = "runtime-global",
		default_value = 600,
		minimum_value = 0,
		maximum_value = 2147483647,
	},
	{
		type = "bool-setting",
		name = "cybersyn-allow-cargo-in-depot",
		order = "cc",
		setting_type = "runtime-global",
		default_value = false,
	},
	{
		type = "double-setting",
		name = "cybersyn-manager-updates-per-second",
		order = "ad",
		setting_type = "runtime-global",
		default_value = 1,
		minimum_value = 0,
		maximum_value = 60,
	},
	{
		type = "bool-setting",
		name = "cybersyn-manager-enabled",
		order = "aa",
		setting_type = "startup",
		default_value = false,
	},
	{
		type = "int-setting",
		name = "cybersyn-manager-result-limit",
		order = "aa",
		setting_type = "runtime-per-user",
		default_value = -1,
		minimum_value = -1,
		maximum_value = 2147483647,
	},
	--{
	--  type = "bool-setting",
	--  name = "cybersyn-disable-top-left-button",
	--  setting_type = "runtime-player",
	--  default_value = false,
	--  order = "ea",
	--},
	--{
	--  type = "int-setting",
	--  name = "cybersyn-history-length",
	--  setting_type = "runtime-global",
	--  minimum_value = 10,
	--  maximum_value = 1000,
	--  default_value = 50,
	--  order = "eb",
	--},
})
