--By Mami
data:extend({
	{
		type = "double-setting",
		name = "cybersyn-ticks-per-second",
		order = "aa",
		setting_type = "runtime-global",
		default_value = 30,
		minimum_value = 0,
		maximum_value = 60,
	},
	{
		type = "int-setting",
		name = "cybersyn-update-rate",
		order = "ab",
		setting_type = "runtime-global",
		default_value = 2,
		minimum_value = 1,
		maximum_value = 2147483647,
	},
	{
		type = "double-setting",
		name = "cybersyn-request-threshold",
		order = "ba",
		setting_type = "runtime-global",
		default_value = 2000,
		minimum_value = 1,
		maximum_value = 2147483647,
	},
	{
		type = "int-setting",
		name = "cybersyn-network-flag",
		order = "bb",
		setting_type = "runtime-global",
		default_value = -1,
		minimum_value = -2147483648,
		maximum_value = 2147483647,
	},
	{
		type = "double-setting",
		name = "cybersyn-fuel-threshold",
		order = "bc",
		setting_type = "runtime-global",
		default_value = .5,
		minimum_value = 0,
		maximum_value = 1,
	},
	{
		type = "double-setting",
		name = "cybersyn-warmup-time",
		order = "ca",
		setting_type = "runtime-global",
		default_value = 20,
		minimum_value = 0,
		maximum_value = 2147483647,
	},
	{
		type = "double-setting",
		name = "cybersyn-stuck-train-time",
		order = "cb",
		setting_type = "runtime-global",
		default_value = 600,
		minimum_value = 0,
		maximum_value = 2147483647,
	},
	{
		type = "bool-setting",
		name = "cybersyn-allow-nonempty-in-depot",
		order = "cc",
		setting_type = "runtime-global",
		default_value = false,
	},
	{
		type = "bool-setting",
		name = "cybersyn-invert-sign",
		order = "da",
		setting_type = "runtime-global",
		default_value = false,
	},
})
