---@meta
---@diagnostic disable

--$Factorio 1.1.72
--$Overlay 5
--$Section builtin
-- This file is automatically generated. Edits will be overwritten.

---A double-precision floating-point number. This is the same data type as all Lua numbers use.
---
---[View documentation](https://lua-api.factorio.com/latest/Builtin-Types.html#double)
---@alias double number

---A floating-point number. This is a single-precision floating point number. Whilst Lua only uses double-precision numbers, when a function takes a float, the game engine will immediately convert the double-precision number to single-precision.
---
---[View documentation](https://lua-api.factorio.com/latest/Builtin-Types.html#float)
---@class float:number
---@operator unm:float
---@operator mod:float
---@operator add:float
---@operator div:float
---@operator sub:float
---@operator mul:float

---32-bit signed integer. Possible values are -2,147,483,648 to 2,147,483,647.
---
---[View documentation](https://lua-api.factorio.com/latest/Builtin-Types.html#int)
---@alias int integer

---8-bit signed integer. Possible values are -128 to 127.
---
---[View documentation](https://lua-api.factorio.com/latest/Builtin-Types.html#int8)
---@class int8:integer
---@operator unm:int8
---@operator mod:int8
---@operator add:int8
---@operator div:int8
---@operator sub:int8
---@operator mul:int8

---32-bit unsigned integer. Possible values are 0 to 4,294,967,295.
---
---[View documentation](https://lua-api.factorio.com/latest/Builtin-Types.html#uint)
---@class uint:integer
---@operator unm:int
---@operator mod:uint
---@operator add:uint
---@operator div:uint
---@operator sub:uint
---@operator mul:uint

---16-bit unsigned integer. Possible values are 0 to 65535.
---
---[View documentation](https://lua-api.factorio.com/latest/Builtin-Types.html#uint16)
---@class uint16:integer
---@operator unm:int16
---@operator mod:uint16
---@operator add:uint16
---@operator div:uint16
---@operator sub:uint16
---@operator mul:uint16

---64-bit unsigned integer. Possible values are 0 to 18,446,744,073,709,551,615.
---
---[View documentation](https://lua-api.factorio.com/latest/Builtin-Types.html#uint64)
---@class uint64:integer
---@operator unm:int64
---@operator mod:uint64
---@operator add:uint64
---@operator div:uint64
---@operator sub:uint64
---@operator mul:uint64

---8-bit unsigned integer. Possible values are 0 to 255.
---
---[View documentation](https://lua-api.factorio.com/latest/Builtin-Types.html#uint8)
---@class uint8:integer
---@operator unm:int8
---@operator mod:uint8
---@operator add:uint8
---@operator div:uint8
---@operator sub:uint8
---@operator mul:uint8


