---@meta
---@diagnostic disable

--$Factorio 1.1.72
--$Overlay 5
--$Section LuaSettings
-- This file is automatically generated. Edits will be overwritten.

---**Global Description:**  
---Allows reading the current mod settings.
---
---**Class Description:**  
---Object containing mod settings of three distinct types: `startup`, `global`, and `player`. An instance of LuaSettings is available through the global object named `settings`.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaSettings.html)
---@class LuaSettings:LuaObject
---[R]  
---The current global mod settings, indexed by prototype name.
---
---Even though these are marked as read-only, they can be changed by overwriting individual [ModSetting](https://lua-api.factorio.com/latest/Concepts.html#ModSetting) tables in the custom table. Mods can only change their own settings. Using the in-game console, all global settings can be changed.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaSettings.html#LuaSettings.global)
---@field global LuaCustomTable<string,ModSetting> 
---[R]  
---This object's name.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaSettings.html#LuaSettings.object_name)
---@field object_name string 
---[R]  
---The default player mod settings for this map, indexed by prototype name.
---
---Even though these are marked as read-only, they can be changed by overwriting individual [ModSetting](https://lua-api.factorio.com/latest/Concepts.html#ModSetting) tables in the custom table. Mods can only change their own settings. Using the in-game console, all player settings can be changed.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaSettings.html#LuaSettings.player)
---@field player LuaCustomTable<string,ModSetting> 
---[R]  
---The startup mod settings, indexed by prototype name.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaSettings.html#LuaSettings.startup)
---@field startup LuaCustomTable<string,ModSetting> 
settings={
---Gets the current per-player settings for the given player, indexed by prototype name. Returns the same structure as [LuaPlayer::mod_settings](https://lua-api.factorio.com/latest/LuaPlayer.html#LuaPlayer.mod_settings).
---
---**Note:** This table will become invalid if its associated player does.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaSettings.html#LuaSettings.get_player_settings)
---@param player PlayerIdentification
---@return LuaCustomTable<string,ModSetting>
get_player_settings=function(player)end,
}


