---@meta
---@diagnostic disable

--$Factorio 1.1.72
--$Overlay 5
--$Section LuaRCON
-- This file is automatically generated. Edits will be overwritten.

---**Global Description:**  
---Allows printing messages to the calling RCON instance if any.
---
---**Class Description:**  
---An interface to send messages to the calling RCON interface.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaRCON.html)
---@class LuaRCON:LuaObject
---[R]  
---This object's name.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaRCON.html#LuaRCON.object_name)
---@field object_name string 
rcon={
---Print text to the calling RCON interface if any.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaRCON.html#LuaRCON.print)
---@param message LocalisedString
print=function(message)end,
}


