---@meta
---@diagnostic disable

--$Factorio 1.1.72
--$Overlay 5
--$Section LuaMiningDrillControlBehavior
-- This file is automatically generated. Edits will be overwritten.

---Control behavior for mining drills.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaMiningDrillControlBehavior.html)
---@class LuaMiningDrillControlBehavior:LuaGenericOnOffControlBehavior
---[RW]  
---`true` if this drill is enabled or disabled using the logistics or circuit condition.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaMiningDrillControlBehavior.html#LuaMiningDrillControlBehavior.circuit_enable_disable)
---@field circuit_enable_disable boolean 
---[RW]  
---`true` if this drill should send the resources in the field to the circuit network. Which resources depends on [LuaMiningDrillControlBehavior::resource_read_mode](https://lua-api.factorio.com/latest/LuaMiningDrillControlBehavior.html#LuaMiningDrillControlBehavior.resource_read_mode)
---
---[View documentation](https://lua-api.factorio.com/latest/LuaMiningDrillControlBehavior.html#LuaMiningDrillControlBehavior.circuit_read_resources)
---@field circuit_read_resources boolean 
---[R]  
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaMiningDrillControlBehavior.html#LuaMiningDrillControlBehavior.object_name)
---@field object_name string 
---[RW]  
---If the mining drill should send just the resources in its area or the entire field it's on to the circuit network.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaMiningDrillControlBehavior.html#LuaMiningDrillControlBehavior.resource_read_mode)
---@field resource_read_mode defines.control_behavior.mining_drill.resource_read_mode 
---[R]  
---The resource entities that the mining drill will send information about to the circuit network or an empty array.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaMiningDrillControlBehavior.html#LuaMiningDrillControlBehavior.resource_read_targets)
---@field resource_read_targets LuaEntity[] 
---[R]  
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaMiningDrillControlBehavior.html#LuaMiningDrillControlBehavior.valid)
---@field valid boolean 
local LuaMiningDrillControlBehavior={
---All methods and properties that this object supports.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaMiningDrillControlBehavior.html#LuaMiningDrillControlBehavior.help)
---@return string
help=function()end,
}


