---@meta
---@diagnostic disable

--$Factorio 1.1.72
--$Overlay 5
--$Section LuaControlBehavior
-- This file is automatically generated. Edits will be overwritten.

---The control behavior for an entity. Inserters have logistic network and circuit network behavior logic, lamps have circuit logic and so on. This is an abstract base class that concrete control behaviors inherit.
---
---**Note:** An control reference becomes invalid once the control behavior is removed or the entity (see [LuaEntity](https://lua-api.factorio.com/latest/LuaEntity.html)) it resides in is destroyed.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaControlBehavior.html)
---@class LuaControlBehavior:LuaObject
---[R]  
---The entity this control behavior belongs to.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaControlBehavior.entity)
---@field entity LuaEntity 
---[R]  
---The concrete type of this control behavior.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaControlBehavior.type)
---@field type defines.control_behavior.type 
local LuaControlBehavior={
---[View documentation](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaControlBehavior.get_circuit_network)
---@param wire defines.wire_type@Wire color of the network connected to this entity.
---@param circuit_connector defines.circuit_connector_id?@The connector to get circuit network for. Must be specified for entities with more than one circuit network connector.
---@return LuaCircuitNetwork@The circuit network or nil.
get_circuit_network=function(wire,circuit_connector)end,
}


