---@meta
---@diagnostic disable

--$Factorio 1.1.72
--$Overlay 5
--$Section LuaDecorativePrototype
-- This file is automatically generated. Edits will be overwritten.

---Prototype of an optimized decorative.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaDecorativePrototype.html)
---@class LuaDecorativePrototype:LuaObject
---[R]  
---Autoplace specification for this decorative prototype, if any.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaDecorativePrototype.html#LuaDecorativePrototype.autoplace_specification)
---@field autoplace_specification? AutoplaceSpecification 
---[R]  
---The bounding box used for collision checking.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaDecorativePrototype.html#LuaDecorativePrototype.collision_box)
---@field collision_box BoundingBox 
---[R]  
---The collision masks this decorative uses
---
---[View documentation](https://lua-api.factorio.com/latest/LuaDecorativePrototype.html#LuaDecorativePrototype.collision_mask)
---@field collision_mask CollisionMask 
---[R]
---
---[View documentation](https://lua-api.factorio.com/latest/LuaDecorativePrototype.html#LuaDecorativePrototype.collision_mask_with_flags)
---@field collision_mask_with_flags CollisionMaskWithFlags 
---[R]
---
---[View documentation](https://lua-api.factorio.com/latest/LuaDecorativePrototype.html#LuaDecorativePrototype.localised_description)
---@field localised_description LocalisedString 
---[R]
---
---[View documentation](https://lua-api.factorio.com/latest/LuaDecorativePrototype.html#LuaDecorativePrototype.localised_name)
---@field localised_name LocalisedString 
---[R]  
---Name of this prototype.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaDecorativePrototype.html#LuaDecorativePrototype.name)
---@field name string 
---[R]  
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaDecorativePrototype.html#LuaDecorativePrototype.object_name)
---@field object_name string 
---[R]  
---The string used to alphabetically sort these prototypes. It is a simple string that has no additional semantic meaning.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaDecorativePrototype.html#LuaDecorativePrototype.order)
---@field order string 
---[R]  
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaDecorativePrototype.html#LuaDecorativePrototype.valid)
---@field valid boolean 
local LuaDecorativePrototype={
---All methods and properties that this object supports.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaDecorativePrototype.html#LuaDecorativePrototype.help)
---@return string
help=function()end,
}


