---@meta
---@diagnostic disable

--$Factorio 1.1.72
--$Overlay 5
--$Section LuaTransportBeltControlBehavior
-- This file is automatically generated. Edits will be overwritten.

---Control behavior for transport belts.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaTransportBeltControlBehavior.html)
---@class LuaTransportBeltControlBehavior:LuaGenericOnOffControlBehavior
---[RW]  
---If the belt will be enabled/disabled based off the circuit network.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaTransportBeltControlBehavior.html#LuaTransportBeltControlBehavior.enable_disable)
---@field enable_disable boolean 
---[R]  
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaTransportBeltControlBehavior.html#LuaTransportBeltControlBehavior.object_name)
---@field object_name string 
---[RW]  
---If the belt will read the contents and send them to the circuit network.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaTransportBeltControlBehavior.html#LuaTransportBeltControlBehavior.read_contents)
---@field read_contents boolean 
---[RW]  
---The read mode for the belt.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaTransportBeltControlBehavior.html#LuaTransportBeltControlBehavior.read_contents_mode)
---@field read_contents_mode defines.control_behavior.transport_belt.content_read_mode 
---[R]  
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaTransportBeltControlBehavior.html#LuaTransportBeltControlBehavior.valid)
---@field valid boolean 
local LuaTransportBeltControlBehavior={
---All methods and properties that this object supports.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaTransportBeltControlBehavior.html#LuaTransportBeltControlBehavior.help)
---@return string
help=function()end,
}


