---@meta
---@diagnostic disable

--$Factorio 1.1.72
--$Overlay 5
--$Section LuaAISettings
-- This file is automatically generated. Edits will be overwritten.

---Collection of settings for overriding default ai behavior.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaAISettings.html)
---@class LuaAISettings:LuaObject
---[RW]  
---If enabled, units that repeatedly fail to succeed at commands will be destroyed.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaAISettings.html#LuaAISettings.allow_destroy_when_commands_fail)
---@field allow_destroy_when_commands_fail boolean 
---[RW]  
---If enabled, units that have nothing else to do will attempt to return to a spawner.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaAISettings.html#LuaAISettings.allow_try_return_to_spawner)
---@field allow_try_return_to_spawner boolean 
---[RW]  
---If enabled, units will try to separate themselves from nearby friendly units.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaAISettings.html#LuaAISettings.do_separation)
---@field do_separation boolean 
---[R]  
---The class name of this object. Available even when `valid` is false. For LuaStruct objects it may also be suffixed with a dotted path to a member of the struct.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaAISettings.html#LuaAISettings.object_name)
---@field object_name string 
---[RW]  
---The pathing resolution modifier, must be between -8 and 8.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaAISettings.html#LuaAISettings.path_resolution_modifier)
---@field path_resolution_modifier int8 
---[R]  
---Is this object valid? This Lua object holds a reference to an object within the game engine. It is possible that the game-engine object is removed whilst a mod still holds the corresponding Lua object. If that happens, the object becomes invalid, i.e. this attribute will be `false`. Mods are advised to check for object validity if any change to the game state might have occurred between the creation of the Lua object and its access.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaAISettings.html#LuaAISettings.valid)
---@field valid boolean 
local LuaAISettings={
---All methods and properties that this object supports.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaAISettings.html#LuaAISettings.help)
---@return string
help=function()end,
}


