---@meta
---@diagnostic disable

--$Factorio 1.1.72
--$Overlay 5
--$Section LuaCombinatorControlBehavior
-- This file is automatically generated. Edits will be overwritten.

---[View documentation](https://lua-api.factorio.com/latest/LuaCombinatorControlBehavior.html)
---@class LuaCombinatorControlBehavior:LuaControlBehavior
---[R]  
---The circuit network signals sent by this combinator last tick.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaCombinatorControlBehavior.html#LuaCombinatorControlBehavior.signals_last_tick)
---@field signals_last_tick Signal[] 
local LuaCombinatorControlBehavior={
---Gets the value of a specific signal sent by this combinator behavior last tick or `nil` if the signal didn't exist.
---
---[View documentation](https://lua-api.factorio.com/latest/LuaCombinatorControlBehavior.html#LuaCombinatorControlBehavior.get_signal_last_tick)
---@param signal SignalID@The signal to get
---@return int?
get_signal_last_tick=function(signal)end,
}


