--By Mami

MISSING_TRAIN_NAME = "cybersyn-missing-train"
LOST_TRAIN_NAME = "cybersyn-lost-train"
NONEMPTY_TRAIN_NAME = "cybersyn-nonempty-train"

SIGNAL_PRIORITY = "cybersyn-priority"
REQUEST_THRESHOLD = "cybersyn-request-threshold"
PROVIDE_THRESHOLD = "cybersyn-provide-threshold"
LOCKED_SLOTS = "cybersyn-locked-slots"

COMBINATOR_NAME = "cybersyn-combinator"
COMBINATOR_OUT_NAME = "cybersyn-combinator-output"

OPERATION_PRIMARY_IO = "*"
OPERATION_SECONDARY_IO = "/"
OPERATION_DEPOT = "+"
OPERATION_WAGON_MANIFEST = "-"

DELTA = 1/2048

STATUS_D = 0
STATUS_D_TO_P = 1
STATUS_P = 2
STATUS_P_TO_R = 3
STATUS_R = 4
STATUS_R_TO_D = 5

TRAIN_LAYOUT_NA = "N"
TRAIN_LAYOUT_CARGO = "C"
TRAIN_LAYOUT_FLUID = "F"
--TRAIN_LAYOUT_ARTILLERY = "A"

STATION_LAYOUT_NA = "N"
STATION_LAYOUT_CARGO = "C"
STATION_LAYOUT_FLUID = "F"
STATION_LAYOUT_BOTH = "."

LONGEST_INSERTER_REACH = 2

TRAIN_CLASS_ALL = "all"
TRAIN_CLASS_AUTO = "auto"
