--By Mami

SIGNAL_PRIORITY = "cybersyn-priority"
REQUEST_THRESHOLD = "cybersyn-r_threshold"
PROVIDE_THRESHOLD = "cybersyn-p_threshold"
LOCKED_SLOTS = "cybersyn-locked-slots"

STATION_IN_NAME = "cybersyn-station-in"
STATION_OUT_NAME = "cybersyn-station-out"
BUFFER_STATION_NAME = "cybersyn-station"
DEPOT_STATION_NAME = "cybersyn-depot"

DELTA = 1/2048

STATUS_D = 0
STATUS_D_TO_P = 1
STATUS_P = 2
STATUS_P_TO_R = 3
STATUS_R = 4
STATUS_R_TO_D = 5

TRAIN_LAYOUT_NA = "N"
TRAIN_LAYOUT_CARGO = "C"
TRAIN_LAYOUT_FLUID = "F"
--TRAIN_LAYOUT_ARTILLERY = "A"

STATION_LAYOUT_NA = "N"
STATION_LAYOUT_CARGO = "C"
STATION_LAYOUT_FLUID = "F"
STATION_LAYOUT_BOTH = "."

LONGEST_INSERTER_REACH = 2
